# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_tasklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tasklist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='todolist.Tasklist'),
            preserve_default=False,
        ),
    ]
