# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 12:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(to='todolist.Tag'),
        ),
    ]
