# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0009_auto_20170401_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasklist',
            name='highlighted',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
