# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0010_auto_20170408_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='highlighted',
        ),
    ]
