# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_auto_20170410_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, default='n', to='todolist.Tag'),
        ),
    ]
