# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-08 21:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0014_auto_20170410_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='available_to',
            field=models.ManyToManyField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL), to=settings.AUTH_USER_MODEL),
        ),
    ]
