# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 19:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0015_task_available_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='available_to',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='available_to',
            field=models.ManyToManyField(blank=True, default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasklists', to=settings.AUTH_USER_MODEL), to=settings.AUTH_USER_MODEL),
        ),
    ]
