# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0004_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='vipuser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vipusers', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
