# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-10 13:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0005_tasklist_vipuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='vipuser',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='vipuser',
            field=models.ManyToManyField(related_name='vipusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
