# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 21:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_auto_20170510_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='vipuser',
        ),
    ]
