# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-15 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0008_remove_task_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tasks',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
