# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0011_remove_task_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='tasks',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='vipuser',
            field=models.ManyToManyField(related_name='vipusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
