# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 10:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0012_auto_20170521_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasklist',
            old_name='vipuser',
            new_name='vipusers',
        ),
    ]
