# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 12:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolist', '0013_auto_20170521_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='view_users',
            field=models.ManyToManyField(related_name='view_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
