# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0014_tasklist_view_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklist',
            name='view_users',
            field=models.ManyToManyField(blank=True, related_name='view_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='vipusers',
            field=models.ManyToManyField(blank=True, related_name='vipusers', to=settings.AUTH_USER_MODEL),
        ),
    ]
